Edgar move problem
moh-tabak/MineSweeper pull request #17
Opened 2022-10-24 12:58 UTC by EaBack

added code for player to be able to lose and check for double move/invalid move

2022-10-24 14:02 UTC, moh-tabak requested changes

2022-10-25 06:51 UTC, EaBack commented on src/Game.java
> +            if(Square.isMineHere=true){
remove, was work in progress, but think Youssef resolved it. otherwise I can work more on it when I updated latest version.

2022-10-25 06:51 UTC, EaBack commented on src/GameBord.java
> +    public static final int ILLEGAL_MOVE = 0;
Ok, do enum instead

2022-10-25 06:54 UTC, EaBack commented on src/GameBord.java
> +            return ILLEGAL_MOVE;
did you build it yet? or did you start? I can finish it than you can throw this out. I did similar in tic-tac-toe, but wasn't sure it would work here

 if(count == boardSize * boardSize){
            return ITS_A_TIE;

in tictactoe I did a count on board size, because then everything would be filled up. 
but here you must take in account the mines yet.

2022-10-25 06:56 UTC, EaBack commented on src/Main.java
I thought I did that, but is this part already fixed by Youssef? I'll update and work further on it otherwise. Than we can scratch this.

2022-10-25 10:30 UTC, closed without merging